version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: src
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Dependencies
          command: npm i -S
      - run:
          name: Docker Build
          command: docker build -f Dockerfile -t clara:continous .
 notify: 
   webhooks:
     - url:  https://discordapp.com/api/webhooks/294663888493084673/YIM9t7gK8vSZrE3HqnlKQNDi8p9XM1tyOlcT9T39MMBLc57GuoK53yxHVKILNKHE-Uhu/circle